SINTEF/SESAR-CWP

src/model/AircraftStore.js
src/model/ConfigurationStore.js
src/model/FlightRoute.js

See https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining

Avoid try/catch and prefer optional chainning

---

.eslintrc.json
package-lock.json
package.json
src/components/SpeedVectors.jsx
src/fixLayer.js
src/fixNameLayer.js
src/messageHandlers.js
src/model/AircraftInfo.js
src/model/AircraftModel.js
src/model/AircraftStore.js
src/model/AirspaceModel.js
src/model/AirspaceStore.js
src/model/AltitudeFilter.js
src/model/ConfigurationModel.js
src/model/ConfigurationStore.js
src/model/ConfigurationTime.js
src/model/CoordinatePair.js
src/model/CwpStore.js
src/model/FixModel.js
src/model/FixStore.js
src/model/FlightRoute.js
src/model/SectorModel.js
src/model/Trajectory.js
src/mqtt.js
src/outlineStyle.js
src/reportWebVitals.js
src/state.js

Fix #40 
Also fixed indenting. Please update your editor settings if it ignores the .editorconfig file. You may want to ignore whitespace in your diff tool.

Migrate from mobx-state-tree to mobx

---

package-lock.json
package.json
src/components/SpeedVectors.jsx

Fix #16
The next step is to use the globably filtered list of flights (not there yet).

Implement speed vectors

---

package-lock.json
package.json
src/AircraftMarker.jsx
src/index.css

- Missing logic to send back information
- Need to look more into scrolling part
- Missing border-colors ( look into if we can use something else to create it ex. classnames)

#23 (only UI), #8

---

src/AircraftMarker.jsx
src/Map.jsx
src/components/FlightRoutes.jsx
src/messageHandlers.js
src/model/AircraftStore.js
src/model/CwpStore.js
src/model/SimulatorStore.js
src/mqtt.js
src/state.js

Implement flight routes

---

src/AircraftMarker.jsx
src/components/BottomNavbar.jsx
src/model/CwpStore.js

Toogle fixes

---

src/mqtt.js

Fix #38
The server uses a weird serialization format but it's not the time to change it.

 Implement client to simulator communication through MQTT

---

src/App.jsx
src/components/CurrentSectorPolygon.jsx
src/components/SectorEdgesPolygon.jsx
src/components/Sectors.jsx
src/index.css
src/model/CurrentRoleConfiguration.js
src/model/RoleConfigurationModel.js
src/state.js

Hope it is enough transparent now - we will see

Label transparency

---

src/Map.jsx
src/components/AircraftMarker.jsx
src/components/AircraftPopup.jsx
src/components/DraggablePopup.css
src/components/DraggablePopup.jsx
src/draggableState.js
src/index.css

Hei, I did some improvements on the dragging of aircraft labels.

Labels drag, v2

---

server/.eslintrc.json
server/package-lock.json
server/package.json
src/components/SectorPolygons.tsx
src/index.css

I went with the solution of adding a wider black line bellow the dashed lines to hide the other lines under them. The order seems random for now, which is probably good enough. 
Fix #10

Make sector polygons overlays nice to look at

---

.eslintrc.json
src/SectorConfiguration.tsx
src/components/AircraftListElement.tsx
src/components/ChangeBearingPopup.tsx
src/components/ChangeNextFixPopup.tsx
src/components/SectorFlightList.tsx
src/components/SectorSideView.tsx
src/index.css
src/messageHandlers.ts
src/model/AircraftStore.ts
src/model/ConfigurationStore.ts
src/model/CwpStore.ts
src/mqtt.ts
tsconfig.json

Toggling feature needs to be tested, the new version of the server doesn't yet give me more than one configuration. Will see if I can find a way to test. 
- Many castings String(), Number() to make typescript happy. If there is another better way I'm all ears 🧊

#11 #9 (small fixes) 

---

src/App.tsx
src/SectorConfiguration.tsx
src/components/ChangeNextFixPopup.tsx
src/components/SectorPolygons.tsx
src/components/SectorSideView.tsx
src/components/Sectors.tsx
src/model/AirspaceStore.ts
src/model/ConfigurationStore.ts
src/mqtt.ts

Toggling sector configuration not finished, but testing that sectors appear after refresh

Render 15 08

---

src/index.css
src/model/AircraftStore.ts
src/model/SimulatorStore.ts

Hide planes with old reports from the map

---

src/components/DistanceMeasurements.tsx
src/components/Map.tsx
src/model/DistanceLine.ts

Distance measurement tool should only be between two points

---

src/components/AircraftListElement.tsx
src/components/BottomNavbar.tsx
src/components/MqttIndicators.tsx
src/index.css
src/model/AircraftModel.ts
src/model/AircraftStore.ts
src/model/AirspaceStore.ts
src/model/ConfigurationModel.ts
src/model/ConfigurationStore.ts
src/model/DistanceLine.ts
src/model/FixModel.ts
src/model/FixStore.ts
src/model/RoleConfigurationModel.ts
src/model/RoleConfigurationStore.ts
src/model/SectorModel.ts
src/mqtt/mqtt.ts

This pull request has a few improvements. 
More improvements are coming, but they require some reorganisation of the source code.

Performances improvement, batch 1

---

src/components/ControllerModal.tsx
src/components/SectorConfiguration.tsx
src/components/TableSectors.tsx
src/index.css

Fix drag mode on the table of sectors.

---

src/components/AircraftListElement.tsx
src/components/AircraftMarker.tsx
src/components/AircraftPopup.tsx
src/components/AircraftPopupContent.tsx
src/components/AltitudeFilterPanel.tsx
src/components/ControllerLabel.tsx
src/components/LimboAircrafts.tsx
src/components/SectorFlightList.tsx
src/components/SectorPolygons.tsx
src/index.css
src/model/AircraftModel.ts
src/model/AircraftStore.ts
src/model/RoleConfigurationStore.ts
src/state.ts

Not finished, but merging slowly but steady to not end up as yesterday (and always new branches 🧷 )

Entering flight fix and div

---

src/components/BottomNavbar.css
src/components/MicrophoneButton.tsx
src/components/VoiceCommandFeedback.css
src/voice/voice.ts

Implement push to talk

---

src/components/AircraftLevelPopup.tsx
src/components/AircraftListElement.tsx
src/components/Map.tsx
src/components/SectorFlightList.tsx
src/index.css

This looks like it works better at least, but not sure it's bullet proof

Scroll to number

---

src/components/LimboAircrafts.tsx
src/model/RoleConfigurationStore.ts

Revert "fixing limbo aircrafts - hope better"

---

src/App.tsx
src/components/SectorSideView.tsx

Erik asked if it was possible to have the sector side view on top of the 3D model, at least for next week. But we should keep both with horizontal and vertical for 💯

adding vertical panes instead of horizontal
